In [2]:
%pip install SQLAlchmey psycopq2-binary pandas openpyxl pyarrow -q

Note: you may need to restart the kernel to use updated packages.

ERROR: Could not find a version that satisfies the requirement SQLAlchmey (from versions: none)
ERROR: No matching distribution found for SQLAlchmey

[notice] A new release of pip available: 22.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [7]:
import sqlalchemy
print(sqlalchemy.__version__)

2.0.50

In [8]:
%pip install pandas

Requirement already satisfied: pandas in c:\users\satya\onedrive\desktop\udemyml\section_7\.venv311\lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\satya\onedrive\desktop\udemyml\section_7\.venv311\lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\satya\onedrive\desktop\udemyml\section_7\.venv311\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\satya\onedrive\desktop\udemyml\section_7\.venv311\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in c:\users\satya\onedrive\desktop\udemyml\section_7\.venv311\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip available: 22.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [9]:
import pandas as pd
from sqlalchemy import create_engine

In [10]:
import sys
print(sys.version)

3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)]

In [11]:
import os

print(os.getcwd())

c:\Users\satya\OneDrive\Desktop\udemyml\Section_7\7_6_assessment

In [12]:
import os

print(os.listdir())

['7_6_assignment.ipynb', 'insurance.csv', 'insurance_from_db.xlsx', 'test.parquet']

In [13]:
CSV_FILE = "insurance.csv"
df_csv = pd.read_csv(CSV_FILE)

In [14]:
df_csv.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [15]:
df_csv.shape

(1338, 7)

In [16]:
#connect to the database
#format => "postgresql://[your_user_name]:[test_password]@[host]:5432/[database_name]"
connection_string = "postgresql://postgres:satya%402005@localhost:5432/ml_db"

engine = create_engine(connection_string)

In [17]:
with engine.connect() as con:
    print("connected sucessfully")

connected sucessfully

In [18]:
query = "SELECT * FROM datasets.insurance"
df_db = pd.read_sql(query, con=engine)

In [19]:
df_db.head()

   age     sex     bmi  children smoker     region     charges
0   19  female  27.900         0    yes  southwest  16884.9240
1   18    male  33.770         1     no  southeast   1725.5522
2   28    male  33.000         3     no  southeast   4449.4620
3   33    male  22.705         0     no  northwest  21984.4700
4   32    male  28.880         0     no  northwest   3866.8552

In [20]:
print(df_csv.shape)
print(df_db.shape)

(1338, 7)
(1338, 7)

In [21]:
%pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\satya\onedrive\desktop\udemyml\section_7\.venv311\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\satya\onedrive\desktop\udemyml\section_7\.venv311\lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip available: 22.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [23]:
import os
print(os.path.exists("insurance_from_db.xlsx"))

True

In [24]:
df_db.to_excel(
    "insurance_from_db.xlsx",
    index=False
)

In [25]:
print(df_db.columns.tolist())
print(df_db.columns.duplicated().any())

['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges']
False

In [26]:
print(df_db.dtypes)

age           int64
sex             str
bmi         float64
children      int64
smoker          str
region          str
charges     float64
dtype: object

In [27]:
%pip install pyarrow==17.0.0

Requirement already satisfied: pyarrow==17.0.0 in c:\users\satya\onedrive\desktop\udemyml\section_7\.venv311\lib\site-packages (17.0.0)
Requirement already satisfied: numpy>=1.16.6 in c:\users\satya\onedrive\desktop\udemyml\section_7\.venv311\lib\site-packages (from pyarrow==17.0.0) (2.4.6)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip available: 22.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [28]:
%pip show pyarrow

Name: pyarrow
Version: 17.0.0
Summary: Python library for Apache Arrow
Home-page:
Author:
Author-email:
License: Apache Software License
Location: c:\Users\satya\OneDrive\Desktop\udemyml\Section_7\.venv311\Lib\site-packages
Requires: numpy
Required-by:
Note: you may need to restart the kernel to use updated packages.

In [29]:
df_db.to_parquet(
    "insurance_from_db.parquet",
    index=False
)

In [30]:
import os

print(os.path.exists("insurance_from_db.xlsx"))
print(os.path.exists("insurance_from_db.parquet"))

True
True

In [31]:
import os

for f in [
    "insurance_from_db.xlsx",
    "insurance_from_db.parquet"
]:
    size_kb = os.path.getsize(f) / 1024
    print(f"{f}: {size_kb:.2f} KB")

insurance_from_db.xlsx: 53.13 KB
insurance_from_db.parquet: 22.51 KB

In [32]:
print(df_csv.shape)
print(df_db.shape)

(1338, 7)
(1338, 7)