In [2]:
print("hello")

hello

In [3]:
%pip install -q pandas numpy

Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
import numpy as np
import pandas as pd

pd.set_option("display.max_columns",50) #display all the cols that present in dataset - max 50

***1.Load the DataSet***

titanic_dataset.csv

In [5]:
df = pd.read_csv("titanic_dataset.csv") #pandas able to read the tinatic dataset

In [6]:
df.shape

(891, 15)

In [7]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

3.Adding few cols for demonstrating data issues

In [8]:
#1 to 891
np.arange(1,4+1)

array([1, 2, 3, 4])

In [9]:
#ID like col
df["passenger_id"] = np.arange(1, len(df)+1) #length of the dataset means 891 but with index values its like 890 so for that purpose we give len(df)+1
df["constant_col"] = 1  #gives 1 for all rows

In [10]:
#create a dirty version of embarked_town
df["embark_town_dirty"] = df["embark_town"].copy()

In [11]:
#select a few random rows(only non-missing)
sample_idx = df["embark_town_dirty"].dropna().sample(6, random_state=42).index #give me a sample of index values, I need to get the 6 values where ["embarked_town_dirty"],remove all the missing values in it and then take a sample of 6 values and then get me the index

In [12]:
sample_idx

Index([281, 435, 39, 418, 585, 804], dtype='int64')

In [13]:

#apply simple dirty transformations
df.loc[sample_idx[0:2], "embark_town_dirty"] = df.loc[sample_idx[0:2], "embark_town_dirty"].str.upper()
df.loc[sample_idx[2:4], "embark_town_dirty"] = df.loc[sample_idx[2:4], "embark_town_dirty"].str.strip().apply(lambda x: f" {x} ")
df.loc[sample_idx[4:6], "embark_town_dirty"] = "unkown"

In [14]:
df.iloc[585]#["embark_town_dirty"] #keep sample_idx values in it you will notice the difference

survived                       1
pclass                         1
sex                       female
age                         18.0
sibsp                          0
parch                          2
fare                       79.65
embarked                       S
class                      First
who                        woman
adult_male                 False
deck                           E
embark_town          Southampton
alive                        yes
alone                      False
passenger_id                 586
constant_col                   1
embark_town_dirty         unkown
Name: 585, dtype: object

In [15]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,passenger_id,constant_col,embark_town_dirty
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,1,1,Southampton
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,2,1,Cherbourg
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,3,1,Southampton
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,4,1,Southampton
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,5,1,Southampton

In [16]:
#ID like col
df["passenger_id"] = np.arange(1, len(df)+1) #length of the dataset means 891 but with index values its like 890 so for that purpose we give len(df)+1
df["constant_col"] = 1  #gives 1 for all rows

#create a dirty version of embarked_town
df["embark_town_dirty"] = df["embark_town"].copy()

#select a few random rows(only non-missing)
sample_idx = df["embark_town_dirty"].dropna().sample(6, random_state=42).index #give me a sample of index values, I need to get the 6 values where ["embarked_town_dirty"],remove all the missing values in it and then take a sample of 6 values and then get me the index

#apply simple dirty transformations
df.loc[sample_idx[0:2], "embark_town_dirty"] = df.loc[sample_idx[0:2], "embark_town_dirty"].str.upper()
df.loc[sample_idx[2:4], "embark_town_dirty"] = df.loc[sample_idx[2:4], "embark_town_dirty"].str.strip().apply(lambda x: f" {x} ")
df.loc[sample_idx[4:6], "embark_town_dirty"] = "unkown"

df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,passenger_id,constant_col,embark_town_dirty
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,1,1,Southampton
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,2,1,Cherbourg
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,3,1,Southampton
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,4,1,Southampton
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,5,1,Southampton

***4.Data quality checklist***

Quick checklist for this video:

-Basic dataset overview
-Missing values summary
-Duplicates
-Data type validation
-Constant and quasi constant columns
-ID like columns
-String inconsistencies
-High null columns
-High zero columns (for numeric features)

***-Basic dataset overview***

In [17]:
df.shape

(891, 18)

In [18]:
df.dtypes

survived               int64
pclass                 int64
sex                      str
age                  float64
sibsp                  int64
parch                  int64
fare                 float64
embarked                 str
class                    str
who                      str
adult_male              bool
deck                     str
embark_town              str
alive                    str
alone                   bool
passenger_id           int64
constant_col           int64
embark_town_dirty        str
dtype: object

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   survived           891 non-null    int64
 1   pclass             891 non-null    int64
 2   sex                891 non-null    str
 3   age                714 non-null    float64
 4   sibsp              891 non-null    int64
 5   parch              891 non-null    int64
 6   fare               891 non-null    float64
 7   embarked           889 non-null    str
 8   class              891 non-null    str
 9   who                891 non-null    str
 10  adult_male         891 non-null    bool
 11  deck               203 non-null    str
 12  embark_town        889 non-null    str
 13  alive              891 non-null    str
 14  alone              891 non-null    bool
 15  passenger_id       891 non-null    int64
 16  constant_col       891 non-null    int64
 17  embark_town_dirty  889 non-null    str
dtypes: bool(2), float64(2), int64(6), str(8)
memory usage: 113.2 KB

In [20]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone', 'passenger_id', 'constant_col', 'embark_town_dirty'],
      dtype='str')

In [21]:
df.nunique()

survived               2
pclass                 3
sex                    2
age                   88
sibsp                  7
parch                  7
fare                 248
embarked               3
class                  3
who                    3
adult_male             2
deck                   7
embark_town            3
alive                  2
alone                  2
passenger_id         891
constant_col           1
embark_town_dirty      7
dtype: int64

In [22]:
df.describe()

,survived,pclass,age,sibsp,parch,fare,passenger_id,constant_col
count,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000,891.000000,891.0
mean,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208,446.000000,1.0
std,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429,257.353842,0.0
min,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000,1.000000,1.0
25%,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400,223.500000,1.0
50%,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200,446.000000,1.0
75%,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000,668.500000,1.0
max,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200,891.000000,1.0

Missing value summary

In [23]:
missing_count = df.isna().sum().sort_values(ascending=False) #descending order
missing_percent = (df.isna().mean() * 100).sort_values(ascending=False) #688/891(100) - percentage
missing_summary = pd.DataFrame(
    {
        "missing_count": missing_count,
        "missing_percent": missing_percent

    }

)
print("Missing Values Summary")
missing_summary

Missing Values Summary

                   missing_count  missing_percent
deck                         688        77.216611
age                          177        19.865320
embark_town_dirty              2         0.224467
embarked                       2         0.224467
embark_town                    2         0.224467
survived                       0         0.000000
pclass                         0         0.000000
parch                          0         0.000000
sibsp                          0         0.000000
sex                            0         0.000000
who                            0         0.000000
class                          0         0.000000
fare                           0         0.000000
adult_male                     0         0.000000
alive                          0         0.000000
alone                          0         0.000000
passenger_id                   0         0.000000
constant_col                   0         0.000000

4.3 Duplicates

In [24]:
duplicates_mask = df.duplicated()
num_duplicates = duplicates_mask.sum()
print("Number of duplicates rows:", num_duplicates)
#if you want to remove duplicates:
df_no_duplicates = df.drop_duplicates()

Number of duplicates rows: 0

In [25]:
pd.Series([False, True, True, False, False]).sum()

np.int64(2)

4.4.Data Type Validation

In [26]:
expected_types = {
    "survived": "int64",
    "pclass": "int64",
    "sex": "category",
    "age": "float64",
    "fare": "float64",
    "embark_town": "category",
    "passenger_id": "int64"
}
print("Data Type Vaalidation:")
for col, expected in expected_types.items():
    if col in df.columns:
        actual=df[col].dtype
        print(f"{col}: actual = {actual}, expected={expected}")

Data Type Vaalidation:
survived: actual = int64, expected=int64
pclass: actual = int64, expected=int64
sex: actual = str, expected=category
age: actual = float64, expected=float64
fare: actual = float64, expected=float64
embark_town: actual = str, expected=category
passenger_id: actual = int64, expected=int64

In [27]:
#example of fixing a data type if needed
df["pclass"] = df["pclass"].astype("int64")

4.5.Constant & Quasi-COnstant columns

In [28]:
n_rows = len(df)
nunique = df.nunique()
constant_cols = nunique[nunique == 1].index.to_list()
print("Constant Cols:", constant_cols)

Constant Cols: ['constant_col']

In [29]:
n_rows = len(df)
nunique = df.nunique()
constant_cols = nunique[nunique == 1].index.to_list()
print("Constant Cols:", constant_cols)

#quasi constant columns
quasi_constant_cols = []
for col in df.columns:
    top_freq = df[col].value_counts(normalize=True, dropna=False).values[0]
    if top_freq>0.95 and col not in constant_cols:
        quasi_constant_cols.append(col)

print("Quasi constant columns (top value more than 95 percent:)", quasi_constant_cols)

Constant Cols: ['constant_col']
Quasi constant columns (top value more than 95 percent:) []

In [30]:
df.nunique()

survived               2
pclass                 3
sex                    2
age                   88
sibsp                  7
parch                  7
fare                 248
embarked               3
class                  3
who                    3
adult_male             2
deck                   7
embark_town            3
alive                  2
alone                  2
passenger_id         891
constant_col           1
embark_town_dirty      7
dtype: int64

In [31]:
#1000x100
#10 cols -> constant values
#1 col -> 10
#2 col -> 500

4.6.ID like columns

columns where number of unique values is closer to number of rows

In [32]:
n_rows = len(df) #This line stores the total number of rows in the DataFrame into the variable n_rows.

id_like_cols = [] #An empty list named id_like_cols is created to store the names of columns that meet the criteria.

for col in df.columns:
    if df[col].nunique(dropna=False) == n_rows:
#The nunique() function counts the number of unique values in the column 
# (including NaN values if dropna=False). If the count of unique values equals the total number of rows, it means every row has a unique value for that column.

        id_like_cols.append(col)

print("ID like columns:", id_like_cols)

ID like columns: ['passenger_id']

***4.7. String Inconsistencies***

In [33]:
object_cols = df.select_dtypes(include=["object"]).columns.to_list()
print("Object or category based columns",object_cols)

#simple clean: strip spaces convert it to lower case
df["embark_town_clean"] = (
 
    df["embark_town_dirty"]
    .astype(str)
    .str.strip()
    .str.lower()
    .replace("Unknown", np.nan)
)

Object or category based columns ['sex', 'embarked', 'class', 'who', 'deck', 'embark_town', 'alive', 'embark_town_dirty']

C:\Users\satya\AppData\Local\Temp\ipykernel_4556\1165144952.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  object_cols = df.select_dtypes(include=["object"]).columns.to_list()

In [34]:
sample_idx

Index([281, 435, 39, 418, 585, 804], dtype='int64')

In [35]:
df.iloc[39]

survived                       1
pclass                         3
sex                       female
age                         14.0
sibsp                          1
parch                          0
fare                     11.2417
embarked                       C
class                      Third
who                        child
adult_male                 False
deck                         NaN
embark_town            Cherbourg
alive                        yes
alone                      False
passenger_id                  40
constant_col                   1
embark_town_dirty     Cherbourg
embark_town_clean      cherbourg
Name: 39, dtype: object

4.8.High null columns

In [36]:
high_null_threshold = 0.4 #40% or more values are missing in columns
high_null_cols = missing_summary[missing_summary["missing_percent"] >= high_null_threshold * 100]
print("Columns with high missing percentage")
print(high_null_cols)

Columns with high missing percentage
      missing_count  missing_percent
deck            688        77.216611

***4.9.High zero columns (numeric)***

In [38]:
numeric_cols = df.select_dtypes(include=[np.number]).columns.to_list()
zero_share = {}
for col in numeric_cols:
    zero_share[col] = (df[col] == 0).mean()
zero_share_series = pd.Series(zero_share).sort_values(ascending=False)
print(zero_share_series)
print("----"*50)
high_zero_threshold = 0.8 #80 percent for more zeros
high_zero_cols = zero_share_series[zero_share_series >= high_zero_threshold]
print("Numeric columns with many zeros:", high_zero_cols )

parch           0.760943
sibsp           0.682379
survived        0.616162
fare            0.016835
age             0.000000
pclass          0.000000
passenger_id    0.000000
constant_col    0.000000
dtype: float64
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Numeric columns with many zeros: Series([], dtype: float64)

In [39]:
df_zeros = df.copy()
df_zeros["col_zeros"] = 0
df_zeros.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,passenger_id,constant_col,embark_town_dirty,embark_town_clean,col_zeros
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,1,1,Southampton,southampton,0
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,2,1,Cherbourg,cherbourg,0
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,3,1,Southampton,southampton,0
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,4,1,Southampton,southampton,0
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,5,1,Southampton,southampton,0

In [40]:
df_zeros = df.copy()
df_zeros["col_zeros"] = 0
numeric_cols = df_zeros .select_dtypes(include=[np.number]).columns.to_list()
zero_share = {}
for col in numeric_cols:
    zero_share[col] = (df_zeros[col] == 0).mean()
zero_share_series = pd.Series(zero_share).sort_values(ascending=False)
print(zero_share_series)
print("----"*50)
high_zero_threshold = 0.8 #80 percent for more zeros
high_zero_cols = zero_share_series[zero_share_series >= high_zero_threshold]
print("Numeric columns with many zeros:", high_zero_cols )

col_zeros       1.000000
parch           0.760943
sibsp           0.682379
survived        0.616162
fare            0.016835
pclass          0.000000
age             0.000000
passenger_id    0.000000
constant_col    0.000000
dtype: float64
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Numeric columns with many zeros: col_zeros    1.0
dtype: float64

In [41]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,passenger_id,constant_col,embark_town_dirty,embark_town_clean
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,1,1,Southampton,southampton
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,2,1,Cherbourg,cherbourg
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,3,1,Southampton,southampton
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,4,1,Southampton,southampton
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,5,1,Southampton,southampton

In [44]:
df_zeros = df.copy()
df_zeros["col_zeros"] = 0
numeric_cols = ["age", "constant_col", "fare", "col_zeros"]
zero_share = {}
for col in numeric_cols:
    zero_share[col] = (df_zeros[col] == 0).mean()
zero_share_series = pd.Series(zero_share).sort_values(ascending=False)
print(zero_share_series)
print("----"*50)
high_zero_threshold = 0.8 #80 percent for more zeros
high_zero_cols = zero_share_series[zero_share_series >= high_zero_threshold]
print("Numeric columns with many zeros:", high_zero_cols )

col_zeros       1.000000
fare            0.016835
constant_col    0.000000
age             0.000000
dtype: float64
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Numeric columns with many zeros: col_zeros    1.0
dtype: float64

Data Quality Checks - Summary

In [45]:
print("Data quality checklist summary")
print("- Shape and columns checked")
print("- Missing values summary created")
print("- Duplicates counted and removable copy created")
print("- Data types compared with expectations")
print("- Constant and quasi constant columns flagged")
print("- ID like columns detected")
print("- String inconsistencies checked and cleaned example")
print("- High null columns identified")
print("- High zero numeric columns identified")

Data quality checklist summary
- Shape and columns checked
- Missing values summary created
- Duplicates counted and removable copy created
- Data types compared with expectations
- Constant and quasi constant columns flagged
- ID like columns detected
- String inconsistencies checked and cleaned example
- High null columns identified
- High zero numeric columns identified