1.Kaggle Dataset

https://www.kaggle.com/datasets/alessandrolobello/the-ultimate-earthquake-dataset-from-1990-2023 - ds1
https://www.kaggle.com/datasets/uciml/pima-indians-diabetes-database -ds2

In [4]:
import sys
print(sys.version)

3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)]

In [5]:
import kagglesdk
print(kagglesdk.__version__)

0.1.27

In [6]:
from kagglesdk.kaggle_env import get_env

In [9]:
import kagglesdk.kaggle_env as ke

print(dir(ke))

['Enum', 'KAGGLE_API_V1_TOKEN_PATH', 'KAGGLE_DATA_PROXY_URL_ENV_VAR_NAME', 'KAGGLE_NOTEBOOK_ENV_VAR_NAME', 'KaggleEnv', 'Path', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', '_env_to_endpoint', '_get_access_token_from_file', 'get_access_token_from_env', 'get_endpoint', 'get_env', 'get_logger', 'is_in_kaggle_notebook', 'logging', 'os']

In [10]:
pip uninstall kagglehub kagglesdk -y

Found existing installation: kagglehub 1.0.1
Uninstalling kagglehub-1.0.1:
  Successfully uninstalled kagglehub-1.0.1
Found existing installation: kagglesdk 0.1.27
Uninstalling kagglesdk-0.1.27:
  Successfully uninstalled kagglesdk-0.1.27
Note: you may need to restart the kernel to use updated packages.

In [12]:
%pip install kagglesdk==0.1.22
%pip install kagglehub==0.3.6

Collecting kagglesdk==0.1.22
  Downloading kagglesdk-0.1.22-py3-none-any.whl (212 kB)
     -------------------------------------- 212.8/212.8 kB 1.6 MB/s eta 0:00:00
Requirement already satisfied: protobuf in c:\users\satya\onedrive\desktop\udemyml\section_7\.venv\lib\site-packages (from kagglesdk==0.1.22) (7.35.0)
Requirement already satisfied: requests in c:\users\satya\onedrive\desktop\udemyml\section_7\.venv\lib\site-packages (from kagglesdk==0.1.22) (2.34.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\satya\onedrive\desktop\udemyml\section_7\.venv\lib\site-packages (from requests->kagglesdk==0.1.22) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in c:\users\satya\onedrive\desktop\udemyml\section_7\.venv\lib\site-packages (from requests->kagglesdk==0.1.22) (3.17)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\satya\onedrive\desktop\udemyml\section_7\.venv\lib\site-packages (from requests->kagglesdk==0.1.22) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\satya\onedrive\desktop\udemyml\section_7\.venv\lib\site-packages (from requests->kagglesdk==0.1.22) (2026.5.20)
Installing collected packages: kagglesdk
Successfully installed kagglesdk-0.1.22
Note: you may need to restart the kernel to use updated packages.

WARNING: There was an error checking the latest version of pip.

Collecting kagglehub==0.3.6
  Downloading kagglehub-0.3.6-py3-none-any.whl (51 kB)
     -------------------------------------- 51.9/51.9 kB 534.4 kB/s eta 0:00:00
Requirement already satisfied: packaging in c:\users\satya\onedrive\desktop\udemyml\section_7\.venv\lib\site-packages (from kagglehub==0.3.6) (26.2)
Requirement already satisfied: requests in c:\users\satya\onedrive\desktop\udemyml\section_7\.venv\lib\site-packages (from kagglehub==0.3.6) (2.34.2)
Requirement already satisfied: tqdm in c:\users\satya\onedrive\desktop\udemyml\section_7\.venv\lib\site-packages (from kagglehub==0.3.6) (4.67.3)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\satya\onedrive\desktop\udemyml\section_7\.venv\lib\site-packages (from requests->kagglehub==0.3.6) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in c:\users\satya\onedrive\desktop\udemyml\section_7\.venv\lib\site-packages (from requests->kagglehub==0.3.6) (3.17)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\satya\onedrive\desktop\udemyml\section_7\.venv\lib\site-packages (from requests->kagglehub==0.3.6) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\satya\onedrive\desktop\udemyml\section_7\.venv\lib\site-packages (from requests->kagglehub==0.3.6) (2026.5.20)
Requirement already satisfied: colorama in c:\users\satya\onedrive\desktop\udemyml\section_7\.venv\lib\site-packages (from tqdm->kagglehub==0.3.6) (0.4.6)
Installing collected packages: kagglehub
Successfully installed kagglehub-0.3.6
Note: you may need to restart the kernel to use updated packages.

WARNING: There was an error checking the latest version of pip.

In [1]:
import kagglehub
print("Success")

Success

c:\Users\satya\OneDrive\Desktop\udemyml\Section_7\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [ ]:
print("hi")

In [1]:
%pip install kagglehub

Collecting kagglehub
  Using cached kagglehub-1.0.1-py3-none-any.whl (70 kB)
Collecting kagglesdk<1.0,>=0.1.22
  Using cached kagglesdk-0.1.27-py3-none-any.whl (229 kB)
Requirement already satisfied: packaging in c:\users\satya\onedrive\desktop\udemyml\section_7\.venv\lib\site-packages (from kagglehub) (26.2)
Collecting pyyaml
  Using cached pyyaml-6.0.3-cp311-cp311-win_amd64.whl (158 kB)
Collecting requests
  Using cached requests-2.34.2-py3-none-any.whl (73 kB)
Collecting tqdm
  Using cached tqdm-4.67.3-py3-none-any.whl (78 kB)
Collecting protobuf
  Using cached protobuf-7.35.0-cp310-abi3-win_amd64.whl (439 kB)
Collecting charset_normalizer<4,>=2
  Using cached charset_normalizer-3.4.7-cp311-cp311-win_amd64.whl (159 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.17-py3-none-any.whl (65 kB)
Collecting urllib3<3,>=1.26
  Using cached urllib3-2.7.0-py3-none-any.whl (131 kB)
Collecting certifi>=2023.5.7
  Using cached certifi-2026.5.20-py3-none-any.whl (134 kB)
Requirement already satisfied: colorama in c:\users\satya\onedrive\desktop\udemyml\section_7\.venv\lib\site-packages (from tqdm->kagglehub) (0.4.6)
Installing collected packages: urllib3, tqdm, pyyaml, protobuf, idna, charset_normalizer, certifi, requests, kagglesdk, kagglehub
Successfully installed certifi-2026.5.20 charset_normalizer-3.4.7 idna-3.17 kagglehub-1.0.1 kagglesdk-0.1.27 protobuf-7.35.0 pyyaml-6.0.3 requests-2.34.2 tqdm-4.67.3 urllib3-2.7.0
Note: you may need to restart the kernel to use updated packages.

WARNING: There was an error checking the latest version of pip.

In [7]:
import os
os.environ["KAGGLE_API_TOKEN"] = "KGAT_0e33bafb3d99845740c7b212b4261499"

In [22]:
import kagglehub

#Download latest version
#path = kagglehub.dataset_download("alessandrolobello/the-ultimate-earthquake-dataset-from-1990-2023")
path = kagglehub.dataset_download("uciml/pima-indians-diabetes-database")
print("Path to dataset files:", path)

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.6), please consider upgrading to the latest version (1.0.0).
Downloading from https://www.kaggle.com/api/v1/datasets/download/uciml/pima-indians-diabetes-database?dataset_version_number=1...

100%|██████████| 8.91k/8.91k [00:00<00:00, 2.28MB/s]

Extracting files...
Path to dataset files: C:\Users\satya\.cache\kagglehub\datasets\uciml\pima-indians-diabetes-database\versions\1

In [31]:
import shutil
shutil.copytree(
    "C:/Users/satya/.cache/kagglehub/datasets/uciml/pima-indians-diabetes-database/versions/1",
   "7_4_load_kaggle_uci_dataset/dataset",
    dirs_exist_ok=True,
)
#shutil.copytree(
   # "/kaggle/input/pima-indians-diabetes-database",
  # "/content/dataset",
  #  dirs_exist_ok=True,
#)

'7_4_load_kaggle_uci_dataset/dataset'

In [29]:
%pip install pandas

Requirement already satisfied: pandas in c:\users\satya\onedrive\desktop\udemyml\section_7\.venv\lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\satya\onedrive\desktop\udemyml\section_7\.venv\lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\satya\onedrive\desktop\udemyml\section_7\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\satya\onedrive\desktop\udemyml\section_7\.venv\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in c:\users\satya\onedrive\desktop\udemyml\section_7\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

WARNING: There was an error checking the latest version of pip.

In [13]:
import pandas as pd

In [32]:
df = pd.read_csv("7_4_load_kaggle_uci_dataset/dataset/diabetes.csv")
#df = pd.read_csv("/content/dataset/diabetes.csv")

In [33]:
df.shape

(768, 9)

In [34]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

2.UCI ML Repository

In [35]:
%pip install ucimlrepo

Requirement already satisfied: ucimlrepo in c:\users\satya\onedrive\desktop\udemyml\section_7\.venv\lib\site-packages (0.0.7)
Requirement already satisfied: pandas>=1.0.0 in c:\users\satya\onedrive\desktop\udemyml\section_7\.venv\lib\site-packages (from ucimlrepo) (3.0.3)
Requirement already satisfied: certifi>=2020.12.5 in c:\users\satya\onedrive\desktop\udemyml\section_7\.venv\lib\site-packages (from ucimlrepo) (2026.5.20)
Requirement already satisfied: numpy>=1.26.0 in c:\users\satya\onedrive\desktop\udemyml\section_7\.venv\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\satya\onedrive\desktop\udemyml\section_7\.venv\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\satya\onedrive\desktop\udemyml\section_7\.venv\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2026.2)
Requirement already satisfied: six>=1.5 in c:\users\satya\onedrive\desktop\udemyml\section_7\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.0.0->ucimlrepo) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

WARNING: There was an error checking the latest version of pip.

In [36]:
from ucimlrepo import fetch_ucirepo

# fetch dataset
iris = fetch_ucirepo(id=53)

# data (as pandas dataframes)
X = iris.data.features
y = iris.data.targets

# metadata
print(iris.metadata)

# variable information
print(iris.variables)

{'uci_id': 53, 'name': 'Iris', 'repository_url': 'https://archive.ics.uci.edu/dataset/53/iris', 'data_url': 'https://archive.ics.uci.edu/static/public/53/data.csv', 'abstract': 'A small classic dataset from Fisher, 1936. One of the earliest known datasets used for evaluating classification methods.\n', 'area': 'Biology', 'tasks': ['Classification'], 'characteristics': ['Tabular'], 'num_instances': 150, 'num_features': 4, 'feature_types': ['Real'], 'demographics': [], 'target_col': ['class'], 'index_col': None, 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 1936, 'last_updated': 'Tue Sep 12 2023', 'dataset_doi': '10.24432/C56C76', 'creators': ['R. A. Fisher'], 'intro_paper': {'ID': 191, 'type': 'NATIVE', 'title': 'The Iris data set: In search of the source of virginica', 'authors': 'A. Unwin, K. Kleinman', 'venue': 'Significance, 2021', 'year': 2021, 'journal': 'Significance, 2021', 'DOI': '1740-9713.01589', 'URL': 'https://www.semanticscholar.org/paper/4599862ea877863669a6a8e63a3c707a787d5d7e', 'sha': None, 'corpus': None, 'arxiv': None, 'mag': None, 'acl': None, 'pmid': None, 'pmcid': None}, 'additional_info': {'summary': 'This is one of the earliest datasets used in the literature on classification methods and widely used in statistics and machine learning.  The data set contains 3 classes of 50 instances each, where each class refers to a type of iris plant.  One class is linearly separable from the other 2; the latter are not linearly separable from each other.\n\nPredicted attribute: class of iris plant.\n\nThis is an exceedingly simple domain.\n\nThis data differs from the data presented in Fishers article (identified by Steve Chadwick,  spchadwick@espeedaz.net ).  The 35th sample should be: 4.9,3.1,1.5,0.2,"Iris-setosa" where the error is in the fourth feature. The 38th sample: 4.9,3.6,1.4,0.1,"Iris-setosa" where the errors are in the second and third features.  ', 'purpose': 'N/A', 'funded_by': None, 'instances_represent': 'Each instance is a plant', 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': None, 'citation': None}}
           name     role         type demographic  \
0  sepal length  Feature   Continuous        None
1   sepal width  Feature   Continuous        None
2  petal length  Feature   Continuous        None
3   petal width  Feature   Continuous        None
4         class   Target  Categorical        None

                                         description units missing_values
0                                                NaN    cm             no
1                                                NaN    cm             no
2                                                NaN    cm             no
3                                                NaN    cm             no
4  class of iris plant: Iris Setosa, Iris Versico...   NaN             no

In [19]:
print(type(X))
print(type(y))

<class 'pandas.DataFrame'>
<class 'pandas.DataFrame'>

In [20]:
X.head()

   sepal length  sepal width  petal length  petal width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2